import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = path => readFileSync(new URL(path, import.meta.url), "utf8");
const entry = read("../docs/community/js/app-report6.js");
const recent = read("../docs/community/js/pages/recentMatches.js");
const card = read("../docs/community/js/components/matchCard.js");
const playerCard = read("../docs/community/js/components/playerMatchCard.js");
const playerSearch = read("../docs/community/js/pages/playerSearch.js");
const css = read("../docs/community/css/matches.css");
const baseCss = read("../docs/community/css/base.css");
const statesCss = read("../docs/community/css/states.css");
const analysisCss = read("../docs/community/css/analysis.css");
const serverAnalysisCss = read("../docs/community/css/analysis-server.css");
const mileageCss = read("../docs/community/css/mileage.css");
const adminCss = read("../docs/community/css/admin.css");
const page = read("../docs/community/index.html");
const scoreboard = read("../docs/community/js/components/scoreboard.js");
const { aiRank } = await import("../docs/community/js/components/scoreboard.js");

assert.doesNotMatch(entry, /Promise\.all\(\[loadRecent\(\),loadLiveMatch\(\)\]\)[\s\S]*applyRoute\(\)/);
assert.match(entry, /await applyRoute\(\);\s*void loadLiveMatch\(\);/);
assert.match(card, /data-lazy-scoreboard/);
assert.doesNotMatch(card, /scoreboard\(match\)/);
assert.match(recent, /placeholder\.outerHTML = scoreboard\(match\)/);
assert.match(playerCard, /data-lazy-scoreboard/);
assert.match(playerSearch, /renderScoreboardRows\(data\.match, userId\)/);
assert.doesNotMatch(playerSearch, /server-stats/);
assert.doesNotMatch(playerSearch, /Promise\.all\(\[\s*apiGet\(`\/api\/community\/players[\s\S]*admin\/replays/);
assert.match(playerSearch, /void hydrateReplayDownloads\(target, internalMatches, userId, guildId\)/);
assert.match(playerSearch, /data-personal-match-feed><\/div>/);
assert.match(css, /content-visibility:auto/);
assert.match(baseCss, /progress\{[^}]*color:var\(--primary\);accent-color:var\(--primary\)/);
assert.match(baseCss, /select:focus-visible,textarea:focus-visible[^}]*var\(--focus-ring\)/);
assert.match(baseCss, /progress::-webkit-progress-value\{background:var\(--primary\)\}/);
assert.match(statesCss, /linear-gradient\(90deg,var\(--surface-raised\),var\(--surface-hover\),var\(--surface-raised\)\)/);
assert.match(analysisCss, /\.analysis-loading,\.compact-analysis-loading\{color:var\(--text-muted\)\}/);
assert.match(serverAnalysisCss, /\.server-analysis-loading\{color:var\(--text-muted\)\}/);
assert.match(mileageCss, /button\.is-loading::before\{[^}]*border-top-color:currentColor/);
assert.doesNotMatch(mileageCss, /accent-color:#[0-9a-f]+/i);
assert.match(adminCss, /\.admin-member-actions input\{accent-color:var\(--primary\)\}/);
assert.match(page, /<script>document\.documentElement\.dataset\.theme=[\s\S]*?<\/script>\s*<link rel="stylesheet"/);
assert.match(scoreboard, /players\.length < 2 \|\| rows\.length !== players\.length/);
assert.match(playerSearch, /bindLazyScoreboards\(feed, pageMatches, userId\);\s*bindExpanders\(feed\)/);
assert.match(playerSearch, /placeholder\.dataset\.state = "loading"/);
assert.match(playerSearch, /placeholder\.dataset\.state = "error"/);
assert.doesNotMatch(playerSearch, /bindLazyScoreboards\(target, internalMatches, userId\)/);
const rankedPlayers = [{aiScore:80},{aiScore:100},{aiScore:80},{aiScore:40}];
assert.deepEqual(aiRank({players:rankedPlayers}, rankedPlayers[0]), {rank:2,total:4});
assert.equal(aiRank({players:[{aiScore:100},{aiScore:null}]}, {aiScore:100}), null);
assert.deepEqual(aiRank({players:[{aiScore:100}]}, {aiScore:100,aiRank:3,aiRankTotal:10}), {rank:3,total:10});

console.log("community loading performance checks passed");
