import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = (path) => readFileSync(new URL(path, import.meta.url), "utf8");
const tokens = read("../docs/community/css/tokens.css");
const layout = read("../docs/community/css/layout.css");
const profile = read("../docs/community/css/profile.css");
const matches = read("../docs/community/css/matches.css");
const styles = read("../docs/community/styles.css");
const playerSearch = read("../docs/community/js/pages/playerSearch.js");
const playerMatchCard = read("../docs/community/js/components/playerMatchCard.js");
const utils = read("../docs/community/js/utils.js");

assert.match(tokens, /--layout-max-width:\s*1120px/);
assert.match(tokens, /--surface-1:\s*#1a1a1c/);
assert.match(tokens, /--accent-primary:\s*#7b68ff/);
assert.match(layout, /\.community-main[^}]+var\(--content\)/);
assert.match(layout, /\.community-home-button\{\s*height:48px/);
assert.match(read("../docs/community/css/ranking.css"), /\.ranking-role\{min-width:78px\}/);
assert.match(styles, /#searchView\{--profile-columns:minmax\(380px,1\.2fr\) minmax\(350px,1\.1fr\) minmax\(315px,\.95fr\);--profile-gap:12px\}/);
assert.match(styles, /#searchView \.search-memory-column:first-child\{grid-column:1\/3\}/);
assert.match(styles, /#searchView \.search-memory-column\.favorites\{grid-column:3\}/);
assert.match(profile, /\.search-memory-column\{display:grid;grid-template-rows:38px 1fr/);
assert.match(profile, /\.search-memory-column\.favorites\{width:auto;max-width:none;justify-self:stretch;border-color:var\(--border-soft\)\}/);
assert.match(profile, /\.search-memory-row\{[^}]*height:34px[^}]*border:1px solid var\(--border-soft\)/);
assert.match(profile, /\.search-memory-star,\.search-memory-remove\{[^}]*width:26px;height:26px[^}]*border-radius:5px/);
assert.match(profile, /profile-dashboard-grid\{grid-template-columns:minmax\(380px,1\.2fr\) minmax\(350px,1\.1fr\) minmax\(315px,\.95fr\)/);
assert.match(profile, /profile-summary-panel>\.profile-rank-switcher\{margin:16px 0 0;padding:0;border:0;background:transparent\}/);
assert.match(profile, /profile-dashboard-grid\{grid-template-columns:minmax\(380px,1\.2fr\) minmax\(350px,1\.1fr\) minmax\(315px,\.95fr\);gap:12px;align-items:start\}/);
assert.match(profile, /role-tier-main\{grid-template-columns:minmax\(104px,1\.15fr\) minmax\(103px,\.9fr\) 48px!important;justify-content:stretch;gap:6px!important;width:100%\}/);
assert.match(profile, /summoner-profile-stack \.summoner-profile-icon\{width:60px!important;height:60px!important\}/);
assert.match(profile, /profile-name-with-icon\{display:grid!important;grid-template-columns:62px minmax\(0,1fr\) auto!important/);
assert.match(profile, /profile-rank-switcher>\.profile-section-title\{margin-bottom:10px\}/);
assert.match(playerSearch, /profile-title-action-row">\$\{equippedTitleBadge\(p\.equippedTitle\)}<\/div><div class="profile-name-main/);
assert.match(playerSearch, /<\/div><div class="profile-refresh-wrap profile-refresh-above-name">/);
assert.match(playerSearch, /role-tier-result/);
assert.doesNotMatch(playerSearch, /roleBadges\(/);
assert.doesNotMatch(playerSearch, /profile-overview profile-overview-compact/);
assert.match(playerSearch, /data-profile-live hidden>● LIVE/);
assert.match(playerSearch, /currentGameForPlayer\(userId, guildId\)/);
assert.match(playerSearch, /profile-equipped-title is-empty"><i aria-hidden="true">◇<\/i><b>칭호 없음<\/b>/);
assert.match(profile, /profile-dashboard-grid>\.associate-stats-panel\{padding:16px\}/);
assert.match(profile, /@media\(max-width:1150px\)[\s\S]+grid-template-columns:minmax\(360px,1\.05fr\) minmax\(350px,1fr\)/);
assert.match(profile, /associate-row[^}]+min-height:42px/);
assert.match(matches, /#recentView,[\s\S]+max-width:100%!important/);
assert.doesNotMatch(playerSearch, /<div class="profile-champion-panel">/);
assert.match(utils, /return `BO\$\{bestOf\}\\n매치 \$\{seriesGame\}`/);
assert.match(matches, /\.match-mode,\.result-meta>div\{white-space:pre-line\}/);
assert.match(matches, /scoreboard-layout\.has-personal-analysis\{[\s\S]+grid-template-columns:minmax\(0,1fr\) minmax\(240px,280px\)!important/);
assert.match(matches, /@media\(max-width:1100px\)[\s\S]+scoreboard-layout\.has-personal-analysis\{grid-template-columns:minmax\(0,1fr\)!important/);
assert.match(matches, /grid-template-columns:82px 108px 44px 72px 92px 84px 96px!important/);
assert.match(matches, /scoreboard-profile-link,[^}]+text-overflow:ellipsis!important/);
assert.match(matches, /#recentView \.match-card \.preview-player\{height:25px/);
assert.match(matches, /score-combat-loadout\{width:82px!important;min-width:82px!important;grid-template-columns:34px 40px!important/);
assert.match(matches, /score-cs-cell\{justify-self:stretch!important;place-items:center!important;text-align:center!important/);
assert.match(matches, /score-damage-cell\{justify-self:stretch!important;align-self:stretch!important;width:96px!important/);
assert.match(styles, /personal-match:is\(\.expanded,:not\(\.expanded\)\) \.personal-summary\{[\s\S]+grid-template-columns:85px 118px 400px minmax\(0,1fr\) 38px!important/);
assert.match(styles, /scoreboard-layout \.score-player-row\{[\s\S]+grid-template-columns:82px 158px 54px 84px 104px 90px 96px!important/);
assert.match(styles, /scoreboard-layout \.score-identity\{width:158px!important;min-width:0!important;padding-left:0!important;gap:8px!important\}/);
assert.match(styles, /html\{scrollbar-gutter:stable\}/);
assert.match(playerMatchCard, /<div class="personal-summary">[\s\S]+<\/div><div class="build-detail-panel">[\s\S]+\$\{details\}<\/article>/);
assert.match(playerSearch, /dataset\.state === "loading" \|\| placeholder\.dataset\.state === "loaded"/);
assert.match(playerSearch, /dataset\.state = "error"/);
assert.doesNotMatch(styles, /\.expanded\s+\*/);

const { bindExpanders } = await import(new URL("../docs/community/js/components/scoreboard.js", import.meta.url));
let expanded = false;
let click;
const card = { classList:{ toggle:()=>{ expanded=!expanded; }, contains:()=>expanded } };
const button = { dataset:{}, textContent:"⌄", closest:()=>card, addEventListener:(_event,handler)=>{ click=handler; } };
const root = { querySelectorAll:(selector)=>selector.includes("expand-match") ? [button] : [] };
bindExpanders(root);
for (const expected of [true,false,true]) { click(); assert.equal(expanded,expected); assert.equal(button.textContent,expected ? "⌃" : "⌄"); }

console.log("community density checks passed");
