import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = (path) => readFileSync(new URL(path, import.meta.url), "utf8");
const page = read("../docs/community/index.html");
const entry = read("../docs/community/js/app-report6.js");
const auth = read("../docs/community/js/auth.js");
const profile = read("../docs/community/js/pages/playerSearch.js");
const profileCss = read("../docs/community/css/profile.css");
const tokens = read("../docs/community/css/tokens.css");
const coachPage = read("../docs/index.html");
const coachShell = read("../docs/css/ui-overhaul.css");

const searchView = page.indexOf('id="searchView"');
const memory = page.indexOf('class="search-memory-panel"');
const searchResults = page.indexOf('id="searchResults"');
assert.ok(searchView < memory && memory < searchResults, "recent searches must belong to searchView");
assert.equal(page.match(/class="search-memory-panel"/g)?.length, 1);
assert.match(entry, /RECENT_SEARCH_LIMIT = 5/);
assert.match(page, /communityProfileMenu/);
assert.match(page, /nav-hierarchy-divider/);
assert.doesNotMatch(page, /class="lucid-brand"[^>]*>\s*<img/);
assert.doesNotMatch(coachPage, /class="lucid-brand"[^>]*>\s*<img/);
assert.match(tokens, /--layout-max-width:\s*1120px/);
assert.match(coachShell, /--layout-max-width:1120px/);
assert.match(tokens, /--header-height:\s*66px/);
assert.match(coachShell, /--header-height:66px/);
for (const token of ["--surface-input", "--favorite", "--favorite-hover"]) assert.match(tokens, new RegExp(token));
assert.doesNotMatch(page, /id="communityLogoutBtn"/);
assert.match(auth, /preferredDisplayName \|\| riotAccounts\[0\]/);
for (const token of ["--surface-hover", "--surface-active", "--primary-hover", "--primary-active", "--nav-hover", "--focus-ring"]) assert.match(tokens, new RegExp(token));
assert.match(profile, /searchParams\.set\("champions", "1"\)/);
assert.match(profile, /rows\.slice\(0, 6\)/);
assert.match(profile, /data\[kind\]\.slice\(0, 5\)/);
assert.match(profile, /function lpTrendPanel/);
assert.match(profile, /player\?\.afterMmr \|\| player\?\.mmr/);
assert.match(profile, /LP_TREND_ROLES = \["전체", "탑", "정글", "미드", "원딜", "서폿"\]/);
assert.match(profile, /bindLpTrend\(target, internalMatches, userId\)/);
assert.match(profile, /normalizeRoleKey\(player\?\.role/);
assert.match(profileCss, /\.lp-trend-chart polyline/);
assert.match(profileCss, /\.profile-dashboard-grid\{align-items:start\}/);
assert.doesNotMatch(profileCss, /\.profile-left-column\{[^}]+minmax\(112px,1fr\)/);
assert.match(profileCss, /text-overflow:ellipsis!important/);
assert.doesNotMatch(profile, /`더 보기 \(\$\{rows\.length\}\)`/);
assert.doesNotMatch(profile, /최근 \$\{Number\(data\.sampleGames/);

console.log("header navigation and champion detail checks passed");
