import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const source = readFileSync(new URL("../docs/community/js/pages/mileage.js", import.meta.url), "utf8");
const entry = readFileSync(new URL("../docs/community/js/app-report6.js", import.meta.url), "utf8");
const page = readFileSync(new URL("../docs/community/index.html", import.meta.url), "utf8");
assert.match(source, /const linked=Boolean\(user\?\.discordConnected/);
assert.match(source, /if\(!linked\).*상품을 보려면 로그인 및 디스코드 연동이 필요합니다\./s);
assert.match(source, /최근 7일 획득 범위/);
assert.match(source, /weeklyEarnedMin/);
for (const tab of ["내전 진행","친구 초대","서버 활동","내전 레벨","환경설정"]) assert.match(source, new RegExp(tab));
assert.match(source, /듀오게임 보상/);
assert.doesNotMatch(source, /동반게임 최소 시간/);
assert.match(source, /scrim_xp_per_match/);
assert.match(source, /duo_match_count/);
assert.match(source, /cache:"no-store"/);
assert.match(source, /과거 내전 소급 허용/);
assert.match(source, /admin\/backfill\/preview/);
assert.match(source, /이미 지급된 포인트는 다시 지급되지 않습니다/);
assert.match(source, /setBackfillBusy\(true,"요청 중\.\.\."\).*소급 작업 요청 중.*await request/s);
assert.match(source, /작업 생성 완료 · 진행상태 확인 중/);
assert.match(source, /setTimeout\(tick,2500\)/);
assert.match(source, /<progress max="100"/);
assert.match(source, /현재 지급/);
assert.match(source, /소급 지급 완료/);
assert.match(source, /소급 지급 실패/);
assert.match(source, /최근 작업 이력/);
assert.match(source, /\["queued","running"\]\.includes\(activeBackfill\?\.status\).*pollBackfill/s);
assert.match(source, /backfillRequestPending/);
assert.match(source, /insufficient_balance/);
assert.match(source, /신규 지급 0P/);
assert.match(source, /data-use-item/);
assert.match(source, /wallet\?page=\$\{transactionPage\}&limit=5/);
assert.match(source, /transactionPagination/);
assert.match(source, /mileageTransactionPager/);
assert.match(entry, /pages\/mileage\.js\?v=20260911shopux1/);
assert.match(page, /styles\.css\?v=20260911shopux1/);
assert.match(page, /app-report6\.js\?v=20260911shopux1/);

console.log("mileage auth gate checks passed");
